config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  root to: 'application#landing'

  resources :creatures, only: [:index, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :show, :create, :update]
  resource :cart, only: [:show, :create, :update, :destroy]
  resources :users, only: [:new, :create]

  namespace :admin do
    get '/dashboard', to: 'users#show'
    get '/dashboard/edit', to: 'users#edit', as: 'edit'
    put '/dashboard/update', to: 'users#update', as: 'update'
    get '/users', to: 'users#index', as: 'users'
    get '/orders', to: 'orders#index', as: 'orders'
    put '/order/:id', to: 'orders#update', as: 'order'
    resources :creatures, except: [:destroy]
  end

  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:category', to: 'categories#show', as: 'category'
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || {}
  end

  def creatures
    contents.keys.map do |key|
      Creature.find(key.to_i)
    end
  end

  def add_creature(creature_id)
    contents[creature_id.to_s] ||= 0
    contents[creature_id.to_s] += 1
  end

  def delete_creature(creature_id)
    contents.delete(creature_id.to_s)
  end

  def total_count
    contents.values.sum
  end

  def total_price
    creatures.reduce(0) do |sum, creature|
      sum + subtotal(creature.id)
    end
  end

  def count_of(creature_id)
    contents[creature_id.to_s]
  end

  def subtotal(creature_id)
    contents[creature_id.to_s] * Creature.find(creature_id).price.to_f
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    creature = Creature.find(params[:creature_id])

    @cart.add_creature(creature.id)
    session[:cart] = @cart.contents

    flash[:notice] = "You now have #{pluralize(@cart.count_of(creature.id), creature.breed)}."

    redirect_back(fallback_location: root_path)
  end

  def index; end

  def show; end

  def update
    if params[:change_quantity] == "increment"
      @cart.contents[params[:creature_id]] += 1
    elsif params[:change_quantity] == "decrement"
      @cart.contents[params[:creature_id]] -= 1 unless @cart.contents[params[:creature_id]].zero?
    end
    session[:cart] = @cart.contents
    redirect_to cart_path
  end

  def destroy
    creature = Creature.find(params[:creature_id])

    c_link = view_context.link_to(creature.breed, creature_path(creature))

    @cart.delete_creature(creature.id)
    session[:cart] = @cart.contents

    flash[:notice] = "Successfully removed #{c_link} from your cart."

    redirect_to cart_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h1>My Cart</h1>
<ul class="cart-creatures">
  <% @cart.creatures.each do |creature| %>
  <li id="cart-creature-<%=creature.id%>">
    <%= image_tag creature.image_url, size: "100x100" %>
    <br>
    Breed: <%= link_to creature.breed, creature_path(creature) %>
    <br>
    Description: <%= creature.description %>
    <br>
    Unit Price: <%= number_to_currency creature.price %>
    <br>
    Quantity: <%= @cart.count_of(creature.id) %>
    <%= button_to "Increase Quantity", cart_path(creature_id: creature.id, change_quantity: "increment"), method: "put" %>
    <%= button_to "Decrease Quantity", cart_path(creature_id: creature.id, change_quantity: "decrement"), method: "put" %>
    <br>
    Subtotal: <%= number_to_currency @cart.subtotal(creature.id) %>
    <br>
    <%= button_to "Remove Item", cart_path(creature_id: creature.id), method: :delete %>
  </li>
  <% end %>
</ul>

<div class="cart-total">
  Total Price: <%= number_to_currency @cart.total_price %>
</div>

<div class="checkout">
  <% if current_user %>
    <%= button_to 'Checkout', orders_path, class: 'checkout-btn' %>
  <% else %>
    <p>
      <%= link_to 'Login', login_path %>
      or
      <%= link_to 'Create Account', new_user_path %>
      to Checkout
    </p>
  <% end %>
</div>