config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  root to: 'application#landing'

  resources :creatures, only: [:index, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :show, :create, :update]
  resource :cart, only: [:show, :create, :update, :destroy]
  resources :users, only: [:new, :create]

  namespace :admin do
    get '/dashboard', to: 'users#show'
    get '/dashboard/edit', to: 'users#edit', as: 'edit'
    put '/dashboard/update', to: 'users#update', as: 'update'
    get '/users', to: 'users#index', as: 'users'
    get '/orders', to: 'orders#index', as: 'orders'
    put '/order/:id', to: 'orders#update', as: 'order'
    resources :creatures, except: [:destroy]
  end

  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:category', to: 'categories#show', as: 'category'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false
  has_many :creatures_categories
  has_many :creatures, through: :creatures_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.includes(:creatures).find_by(name: params[:category])
  end

  def index
    @categories = Category.all
  end
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul class="categories">
  <% @categories.each do |category| %>
  <li id="category-<%=category.id%>">
    <div class="carousel">
      <%= link_to category.name, category_path(category.name), class: 'category_name' %>
      <% category.creatures.each do |creature| %>
      <%= render partial: 'creature_card', locals: {creature: creature} %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%=@category.name.titleize%></h1>
<ul class="category-creatures">
  <% @category.creatures.each do |creature| %>
  <li>
    <%= image_tag creature.image_url %><br>
    Breed: <%= link_to creature.breed, creature_path(creature) %><br>
    Price: <%= creature.price %><br>
    <%= button_to "Add to Cart", cart_path(creature_id: creature.id) %>
  </li>
  <% end %>
</ul>