config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  root to: 'application#landing'

  resources :creatures, only: [:index, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :show, :create, :update]
  resource :cart, only: [:show, :create, :update, :destroy]
  resources :users, only: [:new, :create]

  namespace :admin do
    get '/dashboard', to: 'users#show'
    get '/dashboard/edit', to: 'users#edit', as: 'edit'
    put '/dashboard/update', to: 'users#update', as: 'update'
    get '/users', to: 'users#index', as: 'users'
    get '/orders', to: 'orders#index', as: 'orders'
    put '/order/:id', to: 'orders#update', as: 'order'
    resources :creatures, except: [:destroy]
  end

  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:category', to: 'categories#show', as: 'category'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates_uniqueness_of :username, case_sensitive: false

  has_many :orders

  enum role: %w(user admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_admin, only: [:show, :edit]

  def show; end

  def edit; end

  def update
    current_user.update(user_params)
    flash[:success] = 'Info Updated'
    redirect_to admin_dashboard_path
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end

  def set_admin
    @admin = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'Account created!'
      session[:user_id] = User.last.id

      redirect_to dashboard_path
    else
      flash[:failure] = 'Account creation failed'

      redirect_to new_user_path
    end
  end

  def show
    if current_user
      @user = User.includes(:orders).find(current_user.id)
    else
      flash[:failure] = 'Oops! You must be logged in to do that.'

      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def cancel_link(order)
    return unless order.paid? || order.ordered?

    link_to 'Cancel', order_path(order), method: :put
  end
end

app/views/admin/users/edit.html.erb
<h1>Edit Admin Info</h1>

<%= form_for @admin, method: 'put', url: admin_update_path do |f|  %>

  <%= f.label :username  %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit %>

<% end %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<div class="users">
  <% @users.each do |user| %>
  Username: <%= user.username %>
  Email: <%= user.email %>
  Role: <%= user.role %>
  <br>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="admin-dashboard">
  <h1> Admin Dashboard </h1>
  <div class="profile-info">
    Username: <%= @admin.username %>
    <br>
    Email: <%= @admin.email %>
    <br>
    Role: <%= @admin.role %>
  </div>
  <br>
  <%= link_to 'Edit my Info', admin_edit_path, class: 'btn' %>
  <br>
  <%= link_to 'Users', admin_users_path, class: 'btn' %>
  <br>
  <%= link_to 'Orders', admin_orders_path, class: 'btn' %>
</div>