config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  root to: 'application#landing'

  resources :creatures, only: [:index, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :show, :create, :update]
  resource :cart, only: [:show, :create, :update, :destroy]
  resources :users, only: [:new, :create]

  namespace :admin do
    get '/dashboard', to: 'users#show'
    get '/dashboard/edit', to: 'users#edit', as: 'edit'
    put '/dashboard/update', to: 'users#update', as: 'update'
    get '/users', to: 'users#index', as: 'users'
    get '/orders', to: 'orders#index', as: 'orders'
    put '/order/:id', to: 'orders#update', as: 'order'
    resources :creatures, except: [:destroy]
  end

  get '/dashboard', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:category', to: 'categories#show', as: 'category'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :set_cart

  def landing
    @user = current_user
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  private

  def set_cart
    @cart = Cart.new(session[:cart])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def print_welcome(user)
    message = 'Welcome!'
    message = "Welcome, #{user.username}!" if current_user
    content_tag(:h1, message)
  end
end

app/views/application/_creature_card.html.erb
<div id="creature-<%=creature.id%>">
  <div class="col xl3 l4 m6 s12">
    <div class="carousel-item">

      <div class="card small creature-card">
        <div class="card-image">
          <%= image_tag creature.image_url %>
        </div>
        <div class="card-content">
          Breed: <%= link_to creature.breed, creature_path(creature) %><br>
          Price: <%= creature.price %><br>
        </div>
        <div class="cart-action">
          <%= button_to "Add to Cart", cart_path(creature_id: creature.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/landing.html.erb
<%= print_welcome(@user) %>

<%= button_to 'Shop', categories_path, method: :get, class: 'shop' %>
<% unless current_user  %>
  <%= button_to 'Login', login_path, method: :get, class: 'login' %>
  <%= link_to 'Create account', new_user_path, class: 'new-user' %>
<% end %>